apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: bank-ingress
  namespace: bank

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/actions.canary: >
      {
        "type":"forward",
        "forwardConfig":{
          "targetGroups":[
            {
              "serviceName":"bank-service-blue",
              "servicePort":"80",
              "weight":90
            },
            {
              "serviceName":"bank-service-green",
              "servicePort":"80",
              "weight":10
            }
          ]
        }
      }

spec:
  ingressClassName: alb

  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: canary
            port:
              name: use-annotation
